INSERT INTO RATINGS(USER_ID,MOVIE_ID,RATING,CREATED_AT) VALUES(1,1,3,CURRENT_TIMESTAMP);
INSERT INTO RATINGS(USER_ID,MOVIE_ID,RATING,CREATED_AT) VALUES(2,1,1,CURRENT_TIMESTAMP);
INSERT INTO RATINGS(USER_ID,MOVIE_ID,RATING,CREATED_AT) VALUES(3,1,2,CURRENT_TIMESTAMP);
INSERT INTO RATINGS(USER_ID,MOVIE_ID,RATING,CREATED_AT) VALUES(5,2,5,CURRENT_TIMESTAMP);
INSERT INTO RATINGS(USER_ID,MOVIE_ID,RATING,CREATED_AT) VALUES(1,2,4,CURRENT_TIMESTAMP);
INSERT INTO RATINGS(USER_ID,MOVIE_ID,RATING,CREATED_AT) VALUES(3,3,4,CURRENT_TIMESTAMP);
