INSERT INTO MOVIES(MOVIE_ID,TITLE,GENRE,RELEASE_DATE) VALUES(1,'First Movie','Drama','2015-12-17');
INSERT INTO MOVIES(MOVIE_ID,TITLE,GENRE,RELEASE_DATE) VALUES(2,'Second Movie','Action','2015-06-21');
INSERT INTO MOVIES(MOVIE_ID,TITLE,GENRE,RELEASE_DATE) VALUES(3,'Third Movie','SciFi','2017-03-02');
